Workaround a weird bug...
A basic pip install raise a PBR error

alueError: git history requires a target version of
pbr.version.SemanticVersion(0.2.1), but target version is
pbr.version.SemanticVersion(0.1.0)

Have to investigate that point.